export const ADD_NEW_NOTE = "ADD_NEW_NOTE";
export const UPDATE_NOTE = "UPDATE_NOTE";

export const SET_NEWEST_NOTE_AS_CURRENT = "SET_NEWEST_NOTE_AS_CURRENT";
export const SET_CURRENT_NOTE_ID = "SET_CURRENT_NOTE_ID";

export const TOGGLE_NOTE_DELETION_MODAL = "TOGGLE_NOTE_DELETION_MODAL";
export const DELETE_CURRENT_NOTE = "DELETE_CURRENT_NOTE";

export const TOGGLE_FILTER_POPUP = "TOGGLE_FILTER_POPUP";
export const HIDE_FILTER_POPUP = "HIDE_FILTER_POPUP";
export const SET_FILTER_VALUE = "SET_FILTER_VALUE";
