export const ADD_NEW_NOTE = "ADD_NEW_NOTE";
export const RENAME_NOTE = "RENAME_NOTE";
export const UPDATE_NOTE = "UPDATE_NOTE";

export const SET_NEWEST_NOTE_AS_CURRENT = "SET_NEWEST_NOTE_AS_CURRENT";
export const SET_CURRENT_NOTE_ID = "SET_CURRENT_NOTE_ID";

export const TOGGLE_NOTE_DELETION_MODAL = "TOGGLE_NOTE_DELETION_MODAL";
export const DELETE_NOTE = "DELETE_NOTE";

export const TOGGLE_FILTER_POPUP = "TOGGLE_FILTER_POPUP";
export const HIDE_FILTER_POPUP = "HIDE_FILTER_POPUP";
export const SET_FILTER_VALUE = "SET_FILTER_VALUE";

export const TOGGLE_SORT_POPUP = "TOGGLE_SORT_POPUP";
export const HIDE_SORT_POPUP = "HIDE_SORT_POPUP";
export const SET_SORT_VALUE = "SET_SORT_VALUE";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

export const SET_DROPBOX_SYNC_ENABLED = "SET_DROPBOX_SYNC_ENABLED";
export const SET_DROPBOX_ACCESS_TOKEN = "SET_DROPBOX_ACCESS_TOKEN";
export const SET_NOTE_SYNC_STATUS = "SET_NOTE_SYNC_STATUS";
